# Generated by Django 3.1.6 on 2021-02-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('hall', models.CharField(max_length=50)),
            ],
        ),
    ]
